# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :android do
    lane :screenshots do
        build_android_app(
            task: 'assemble',
            build_type: 'Debug'
        )
        build_android_app(
            task: 'assemble',
            build_type: 'AndroidTest'
        )
        capture_android_screenshots(
            locales: ["en-US", "de-DE"],
            clear_previous_screenshots: true,
            skip_open_summary: true,
            use_timestamp_suffix: false,
            app_apk_path: "build/outputs/apk/androidTest/googlePlay/debug/Tammy-googlePlay-debug-androidTest.apk",
            tests_apk_path: "build/outputs/apk/googlePlay/debug/Tammy-googlePlay-debug.apk",
            device_type: "phone",
            specific_device: "emulator-5564"
        )
        capture_android_screenshots(
            locales: ["en-US", "de-DE"],
            clear_previous_screenshots: true,
            skip_open_summary: true,
            use_timestamp_suffix: false,
            app_apk_path: "build/outputs/apk/androidTest/googlePlay/debug/Tammy-googlePlay-debug-androidTest.apk",
            tests_apk_path: "build/outputs/apk/googlePlay/debug/Tammy-googlePlay-debug.apk",
            device_type: "sevenInch",
            specific_device: "emulator-5566"
        )
        capture_android_screenshots(
            locales: ["en-US", "de-DE"],
            clear_previous_screenshots: true,
            skip_open_summary: true,
            use_timestamp_suffix: false,
            app_apk_path: "build/outputs/apk/androidTest/googlePlay/debug/Tammy-googlePlay-debug-androidTest.apk",
            tests_apk_path: "build/outputs/apk/googlePlay/debug/Tammy-googlePlay-debug.apk",
            device_type: "tenInch",
            specific_device: "emulator-5568"
        )
    end

    lane :releaseBeta do
        upload_to_play_store(
            track: 'beta',
            skip_upload_apk: true,
            aab: "build/outputs/bundle/googlePlayRelease/Tammy-googlePlay-release.aab",
            version_code: ENV['CI_PIPELINE_IID']
        )
    end

    lane :release do
        upload_to_play_store(
            skip_upload_apk: true,
            aab: "build/outputs/bundle/googlePlayRelease/Tammy-googlePlay-release.aab",
            version_code: ENV['CI_PIPELINE_IID']
        )
    end
end

# https://stackoverflow.com/a/51027545
platform :ios do
    lane :beta do
        install_provisioning_profile(path: "tammy.mobileprovision")
        import_certificate(
            certificate_path: "dist.cer",
            keychain_name: "apple_keychain.keychain",
            keychain_password: ENV['APPLE_KEYCHAIN_PASSWORD'],
        )
        import_certificate(
            certificate_path: "dist.p12",
            keychain_name: "apple_keychain.keychain",
            keychain_password: ENV['APPLE_KEYCHAIN_PASSWORD'],
        )
        unlock_keychain(
            path: "apple_keychain.keychain",
            password: ENV['APPLE_KEYCHAIN_PASSWORD'],
            set_default: true,
        )
        sh("security find-identity -v -p codesigning")
        update_code_signing_settings(
            use_automatic_signing: false,
            path: "iosApp/iosApp.xcodeproj",
            team_id: "C6CHAMK5QZ",
            bundle_identifier: "de.connect2x.tammy",
            targets: "Tammy for iOS",
        )
        build_app(project: "iosApp/iosApp.xcodeproj",
                  scheme: "Tammy for iOS",
                  export_method: "app-store",
        )
        update_code_signing_settings(
                  use_automatic_signing: true,
                  path: "iosApp/iosApp.xcodeproj",
                  team_id: "C6CHAMK5QZ",
                  bundle_identifier: "de.connect2x.tammy",
        )
        upload_to_testflight
    end
end

platform :ios do
    lane :screenshots do
        capture_screenshots
    end
end

